/**
 * Reading and extracting a catalog bundle.
 *
 * Every archive here was written by Python's `zipfile`, not by this code —
 * a reader tested only against archives it produced itself proves nothing
 * about the format. `tests/fixtures-zip.json` holds them base64-encoded,
 * regenerated by the script in its header comment.
 *
 * The archive is untrusted, so the safety cases are the point: a path that
 * escapes the destination must fail the whole install and leave nothing
 * behind, since a half-written directory is what a later run would read as
 * a cache hit.
 */

import assert from 'node:assert/strict'
import { readFile, readdir, mkdtemp } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'
import { bundleRoot, extractBundle } from '../src/bundle.ts'
import { resolveRefs } from '../src/refs.ts'
import { readZipEntries } from '../src/zip.ts'

const HERE = dirname(fileURLToPath(import.meta.url))
const FIXTURES: Record<string, string> = JSON.parse(
  await readFile(join(HERE, 'fixtures-zip.json'), 'utf8'),
)

/** One fixture archive, as bytes. */
function archive(name: keyof typeof FIXTURES | string): Buffer {
  const encoded = FIXTURES[name]
  assert.ok(encoded, `no fixture named ${name}`)
  return Buffer.from(encoded, 'base64')
}

async function scratch(): Promise<string> {
  return join(await mkdtemp(join(tmpdir(), 'bundle-')), 'cache-entry')
}

test('reads the entries a Python-written archive contains', () => {
  const entries = readZipEntries(archive('wrapped'))
  assert.deepEqual(
    entries.map((e) => e.name).sort(),
    ['pdf-forms/SKILL.md', 'pdf-forms/references/naming.md', 'pdf-forms/scripts/fill.sh'],
  )
  const skill = entries.find((e) => e.name.endsWith('SKILL.md'))!
  assert.match(skill.read().toString('utf8'), /name: pdf-forms/)
})

test('reads a stored entry as well as a deflated one', () => {
  const [only] = readZipEntries(archive('stored'))
  assert.equal(only!.read().toString('utf8'), 'stored\n')
})

test('refuses bytes that are not an archive', () => {
  assert.throws(() => readZipEntries(Buffer.from('not a zip at all')), /not a zip archive/)
})

test('extracts a wrapped bundle and collapses the wrapper', async () => {
  const destination = await scratch()
  await extractBundle(archive('wrapped'), destination)

  // The archive wraps everything in `pdf-forms/`, so the skill's own paths
  // are relative to that, not to the extraction root.
  const root = await bundleRoot(destination)
  assert.equal(root, join(destination, 'pdf-forms'))
  assert.ok(existsSync(join(root, 'SKILL.md')))
  assert.ok(existsSync(join(root, 'scripts/fill.sh')))
  assert.ok(existsSync(join(root, 'references/naming.md')))
})

test('keeps the extraction root for a flat archive', async () => {
  const destination = await scratch()
  await extractBundle(archive('flat'), destination)
  assert.equal(await bundleRoot(destination), destination)
})

test('a traversal attempt fails the install and leaves nothing behind', async () => {
  const destination = await scratch()
  await assert.rejects(() => extractBundle(archive('traversal'), destination), /unsafe zip path/)
  assert.equal(existsSync(destination), false, 'a failed install must not look like a cache hit')
  // Nor may the staging directory survive to be found later.
  const parent = dirname(destination)
  assert.deepEqual(await readdir(parent), [])
})

test('a disallowed suffix is skipped, not fatal', async () => {
  const destination = await scratch()
  await extractBundle(archive('disallowed'), destination)
  assert.ok(existsSync(join(destination, 'SKILL.md')), 'one stray file must not lose the skill')
  assert.equal(existsSync(join(destination, 'run.exe')), false)
})

test('a second extraction over an existing directory is left alone', async () => {
  const destination = await scratch()
  await extractBundle(archive('wrapped'), destination)
  const before = await readFile(join(destination, 'pdf-forms/SKILL.md'), 'utf8')
  await extractBundle(archive('flat'), destination)
  assert.equal(await readFile(join(destination, 'pdf-forms/SKILL.md'), 'utf8'), before)
})

test('an extracted bundle is what makes its body resolvable', async () => {
  // The whole point of extracting: before it, `{baseDir}/scripts/fill.sh`
  // and `references/naming.md` name nothing, and the model is told to open
  // files that are not there.
  const destination = await scratch()
  await extractBundle(archive('wrapped'), destination)
  const root = await bundleRoot(destination)
  const body = await readFile(join(root, 'SKILL.md'), 'utf8')

  const { body: resolved } = resolveRefs(body, root)
  assert.ok(resolved.includes(join(root, 'scripts/fill.sh')))
  assert.ok(resolved.includes(join(root, 'references/naming.md')))
  assert.ok(!resolved.includes('{baseDir}'))
})

test('an archive that understates a size is stopped while inflating', () => {
  // The size check alone catches this, but only after the bytes are in
  // memory — which is the cost the bomb exists to impose. `maxOutputLength`
  // makes the inflate itself refuse, so the error comes from zlib rather
  // than from the comparison below it.
  const [only] = readZipEntries(archive('understated'))
  assert.equal(only!.declaredSize, 32)
  assert.throws(() => only!.read(), (error: Error) => {
    assert.doesNotMatch(error.message, /inflated to/, 'the size check ran, so nothing was capped')
    return true
  })
})
